version: '3'

services:
  dotnetcorewebapponlinuxcontainer1:
    image: dotnetcorewebapponlinuxcontainer1
    build:
      context: ./DotNetCoreWebAppOnLinuxContainer1
      dockerfile: Dockerfile

  dotnetcorewebapponlinuxcontainer2:
    image: dotnetcorewebapponlinuxcontainer2
    build:
      context: ./DotNetCoreWebAppOnLinuxContainer2
      dockerfile: Dockerfile
